create table users (
  id int generated by default as identity (start with 1) primary key,
  code varchar(25) not null,
  name varchar(25) not null,
  score int not null,
  languages varchar(25) not null
);